version: '3.1'
services:
  store-server:
    build: .
    container_name: store-server-container
    ports:
      - "8080:8080"
    depends_on:
      - store-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-db:5432/store-electronics
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  store-db:
    image: postgres:14-alpine
    container_name: store-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=store-electronics
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: YandexStore23
    ports:
      - "5050:80"